version: '3.8'
services:
  frontend:
    container_name: entravision-frontend
    build:
      context: ./../entravision-app 
      dockerfile: Dockerfile 
    restart: always
    ports:
      - '4200:4200'  
    networks:
      - mynetwork
  backend:    container_name: entravision-backend
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/entravision
    links:
      - mongo
    networks:
      - mynetwork
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
